### ISSUE TITLE
Do you plan to move this into core?

### ISSUE THREAD

**Issue by Bre77** [andrewgierens/tessie_hacs_integration#1]
Hey Andrew,

[I just started working on a core integration for Tessie today,](https://github.com/Bre77/core/tree/tessie/homeassistant/components/tessie) but then found you have already done a lot of work in this custom integration.

Do you plan on bringing this code into core, or keeping it in HACS? I'm happy to collaborate if you do.

If do not have any desire to more into core, I dont blame you because it can be a nightmare, but I might keep trying seperately.

**Comment by andrewgierens** [comment]
Hey @Bre77, I did have plan on moving it to core but for the meantime I added it to hacs so I could add it to my "Prod" hass.

I would love to collaborate on it. How should we do it?

**Comment by Bre77** [comment]
I am making some good progress, as I have completed Sensors with 100% test coverage. Just waiting for a core team member to review and approve the PR:
https://github.com/home-assistant/core/pull/104684

Once thats approved I will push Climate and Device Tracker:
https://github.com/Bre77/core/tree/tessie-climate
https://github.com/Bre77/core/tree/tessie-tracker

How you could contribute is to either:
- Raise PRs against any of my branches for things you think we should add or improve.
- Fork https://github.com/Bre77/core/tree/tessie and add additional platforms.
If you do, add yourself as a CODEOWNER in the process (hopefully you have signed the CLA).

**Comment by Bre77** [comment]
Ive also finished Binary Sensors today. https://github.com/Bre77/core/tree/tessie-binary
Probably going to do Numbers next.

It may easiest if you just review those branches and raise PRs for anything you think I have missed.

**Comment by andrewgierens** [comment]
Outcome: Will likely deprecate this integration once the core module is fully featured and merged.
