### ISSUE TITLE
Range showing wrong units.

### ISSUE THREAD

**Issue by Ed-M72** [andrewgierens/tessie_hacs_integration#3]
Both the ideal range and estimated range are incorrectly showing in KM in Home Assistant rather than Miles as shown in Tessie.

E.g. In Tessie 213m, in HomeAssistant 213 km.

Looks like the below two sensors are incorrect in sensor.py

    SensorEntityDescription(
        translation_key="battery_range",
        key="last_state.charge_state.battery_range",
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        device_class=SensorDeviceClass.DISTANCE,
    ),

    SensorEntityDescription(
        translation_key="est_battery_range",
        key="last_state.charge_state.est_battery_range",
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        device_class=SensorDeviceClass.DISTANCE,
    ),

**Comment by andrewgierens** [comment]
You're right, seems their API always gives you the measurement in miles (no matter where you are). Will look at updating this tonight

FYI, this integration will be superseded by the official integration in the coming months, more info [here](https://github.com/home-assistant/core/pull/104684) :)

**Comment by andrewgierens** [comment]
Should be resolved now @Ed-M72 thanks :)
